package-lock.json
package.json
src/components/ContentListTable/ContentListChips.tsx
src/components/ContentListTable/ContentListContext.tsx
src/components/ContentListTable/ContentListFilters.tsx
src/components/ContentListTable/ContentListTable.tsx
src/components/DropdownSelect/DropdownSelect.tsx
src/components/Hide/Hide.tsx
src/pages/ContentPage/ContentPage.tsx
src/services/Content/ContentApi.ts
src/services/Content/ContentQueries.ts
src/services/useDebounce.tsx

**Adds:** 
- `ContentListFilters.tsx`
- `ContentListChips.tsx`
- `DropdownSelect.tsx`
- ~~`ContentListToolbar.tsx`~~
ContentListFilters, ContentListChips, and DropdownSelect all work nicely together with the existing table to make the search bar with filters. This is what I had originally (and what ContentListTable currently renders).
~~_Then_, I found the [patternfly Toolbar component](https://www.patternfly.org/v4/components/toolbar/), which is maybe what I should've used, so I tried implementing the same thing with that. But, that implementation is still buggy and seems a lot messier than the first one.~~ Not using this.
Still needs

Fixes 79: Search and filter content sources list

---

deployments/frontend.yaml

Refs 146: Fix IMAGE param

---

.rhcicd/pr_check.sh

15 was from the template, didn't catch .nvmrc has 16 as the major version.
Set it dynamically so we don't have to update it in multiple places.

Refs 106: Set NODE_BUILD_VERSION from .nvmrc in pr_check

---

src/components/AddContent/AddContent.tsx
src/components/ContentListTable/components/EmptyTableState.tsx

Include one for clear_filters on empty table state.
First of many to come, starting small.
Abusing pr_checks a bit here to get this built and deployed to verify.

Refs 118: Add ouiaID to AddContent button

---

src/components/AddContent/AddContent.tsx

Adding them as I need them, using these PRs to get container images for ephemeral testing.

Refs 118: ouia ID for add modal

---

src/components/AddContent/AddContent.test.tsx
src/components/AddContent/AddContent.tsx
src/components/ContentListTable/ContentListFilters.tsx
src/components/ContentListTable/ContentListTable.test.tsx
src/components/ContentListTable/ContentListTable.tsx
src/components/ContentListTable/components/EmptyTableState.test.tsx
src/components/ContentListTable/components/EmptyTableState.tsx
src/components/ContentListTable/components/PackageCount.tsx
src/components/ContentListTable/components/StatusIcon.tsx
src/components/EditContentModal/EditContentModal.tsx
src/components/Error/ErrorPage.test.tsx
src/components/Error/ErrorPage.tsx
src/components/UrlWithLinkIcon/UrlWithLinkIcon.tsx
src/pages/ContentPage/ContentPage.tsx
src/services/Content/ContentApi.ts
src/services/Content/ContentQueries.ts

Updates:
- First column content, Name/url
- Naming of the overall app.  Use "custom repositories" not "content sources"
- Update table styling to match: [design mocks](https://marvelapp.com/prototype/e1150c1/screen/88547707)

Fixes 158: Update UI to match demo Mocks

---

src/components/AddContent/AddContent.tsx
src/components/EditContentModal/EditContentModal.tsx

Hello
Further to 
https://github.com/content-services/content-sources-frontend/pull/47
Adding some more OUIA IDs for the edit form and fixing surrounding tool tips.
https://issues.redhat.com/browse/HMSCONTENT-184

Refs 184: add ouia and tooltips

---

src/components/ContentListTable/components/AddContent/AddContent.tsx
src/components/ContentListTable/components/EditContentModal/EditContentModal.tsx

Hello
Add more ouia IDs, this time for name and  URL fields
Thank you

Refs 184: add ouia ID for name and url

---

src/components/ContentListTable/components/AddContent/AddContent.tsx
src/components/ContentListTable/components/EditContentModal/EditContentModal.tsx

Hi
Adding some ouiaIds in DropdownSelect so they propagate to Select
Thank you

Refs 184: Add ouiaIds to DropdownSelect

---

.rhcicd/build_deploy.sh
.rhcicd/pr_check.sh

Fixes a version issue with the build_deploy script

---

src/components/ContentListTable/components/EditContentModal/EditContentModal.tsx

Hi
need to add some more ouiaId, this time for buttons.
I could not figure out how to add one for the x close in the top right corner of the modal.

Refs 184: Add ouiaid for edit modal buttons

---

deploy/frontend.yaml

so that we can use the settings navigation

Refs 231: add /settings route

---

README.md

start:beta doesn't actually work
and i need a commit to try the -build push

Refs 214: fix readme mistake

---

src/components/ConditionalTooltip/ConditionalTooltip.test.tsx
src/components/ConditionalTooltip/ConditionalTooltip.tsx
src/components/ContentListTable/components/AddContent/AddContent.test.tsx
src/components/ContentListTable/components/AddContent/AddContent.tsx
src/components/ContentListTable/components/EmptyTableState.tsx

The above button was not being disabled when write permissions were not present.

Fixes 284: No permissions on initial Add content screen

---

src/Pages/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx

This adds a small fix to the Save button to ensure that it won't be accessible between validation calls.

Fixes 294: Save button on edit modal

---

src/Pages/ContentListTable/ContentListTable.tsx
src/Pages/ContentListTable/components/EmptyTableState.tsx
src/Pages/PopularRepositoriesTable/PopularRepositoriesTable.tsx
src/Routes.tsx

Updated an aria label as well to be accurate.

Refs 309: Add/Update ouiaIds for popular/custom tables

---

.rhcicd/pr_check.sh

Fixes 291: Add iqe-tests to pr_check

---

.github/workflows/content-sources-actions.yml

release pipeline wasn't working because its dependent on the testing one

Refs 306: run tests on prod-beta

---

src/Pages/ContentListTable/components/AddContent/AddContent.test.tsx
src/Pages/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/ContentListTable/components/AddContent/helpers.test.ts
src/Pages/ContentListTable/components/AddContent/helpers.ts
src/Pages/ContentListTable/components/EditContentModal/EditContentModal.test.tsx
src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx
src/Pages/ContentListTable/components/EditContentModal/helpers.test.ts
src/services/Notifications/Notifications.tsx

To Test:
1.  Try to drag and drop a file that is bigger than ~8096 bytes
2.  Try to upload a file via the file picker that is bigger than ~8096 bytes
3.  Try to drag and drop more than one file
4.  Try to think of other issues?

Fixes 1130: toast on failed file upload

---

package-lock.json
package.json
src/Pages/ContentListTable/ContentListTable.test.tsx
src/Pages/ContentListTable/ContentListTable.tsx
src/Pages/ContentListTable/components/AddContent/AddContent.test.tsx
src/Pages/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/ContentListTable/components/AddContent/helpers.test.ts
src/Pages/ContentListTable/components/AddContent/helpers.ts
src/Pages/ContentListTable/components/EditContentModal/EditContentModal.test.tsx
src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx
src/Pages/ContentListTable/components/EditContentModal/helpers.test.ts
src/Pages/ContentListTable/components/PackageCount.test.tsx
src/Pages/ContentListTable/components/PackageCount.tsx
src/Pages/ContentListTable/components/PackageModal/PackageModal.test.tsx
src/Pages/ContentListTable/components/StatusIcon.test.tsx
src/Pages/ContentListTable/components/StatusIcon.tsx
src/Pages/ContentListTable/components/StatusText.tsx
src/services/Content/ContentApi.ts
src/services/Content/ContentQueries.ts
src/services/Notifications/Notifications.tsx

This adds:
- "Introspect Now" action to the kebab
- Replaces the status tooltip with a popover that shows some new information and has a "retry" button for introspection
This depends on this backend PR: https://github.com/content-services/content-sources-backend/pull/221
Todo:

Fixes 533: add introspect button and popover

---

.github/pull_request_template.md
deploy/frontend.yaml
package-lock.json
package.json
src/Pages/ContentListTable/ContentListTable.test.tsx
src/Pages/ContentListTable/ContentListTable.tsx
src/Pages/ContentListTable/components/AddContent/AddContent.test.tsx
src/Pages/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/ContentListTable/components/AddContent/helpers.test.ts
src/Pages/ContentListTable/components/AddContent/helpers.ts
src/Pages/ContentListTable/components/EditContentModal/EditContentModal.test.tsx
src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx
src/Pages/ContentListTable/components/EditContentModal/helpers.test.ts
src/Pages/ContentListTable/components/PackageCount.test.tsx
src/Pages/ContentListTable/components/PackageCount.tsx
src/Pages/ContentListTable/components/PackageModal/PackageModal.test.tsx
src/Pages/ContentListTable/components/StatusIcon.test.tsx
src/Pages/ContentListTable/components/StatusIcon.tsx
src/Pages/ContentListTable/components/StatusText.tsx
src/services/Content/ContentApi.ts
src/services/Content/ContentQueries.ts
src/services/Notifications/Notifications.tsx

Update prod beta from latest master

prod beta update

---

src/Pages/ContentListTable/components/AddContent/AddContent.test.tsx
src/Pages/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/ContentListTable/components/AddContent/helpers.test.ts
src/Pages/ContentListTable/components/AddContent/helpers.ts
src/Pages/ContentListTable/components/ContentListFilters.test.tsx
src/Pages/ContentListTable/components/ContentListFilters.tsx
src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx
src/Pages/ContentListTable/components/EditContentModal/helpers.test.ts
src/components/DropdownSelect/DropdownSelect.tsx
src/services/Notifications/Notifications.tsx
src/services/useDebounce.tsx

Updated react tests to cover the contentListFilters component.
Additional Changes: 
- Fixed a bug within useDebounce that was causing rerenders due to a pendo.js timer.

Fixes 1171:  Add react tests for contentListFilters

---

.github/workflows/content-sources-actions.yml

run build flow on prod-stable

---

.github/workflows/build-repo.yml
.github/workflows/content-sources-actions.yml
src/Pages/ContentListTable/components/ContentListFilters.test.tsx
src/Pages/ContentListTable/components/ContentListFilters.tsx
src/components/DropdownSelect/DropdownSelect.tsx
src/services/useDebounce.tsx

force prod-stable build

---

src/Pages/ContentListTable/components/AddContent/helpers.test.ts
src/Pages/ContentListTable/components/AddContent/helpers.ts
src/Routes.tsx
src/components/Header/Header.tsx
src/components/QuickStart/QuickStart.test.tsx
src/components/QuickStart/QuickStart.tsx

Adds a quickstart link to the header of our app. 
[Design here](https://miro.com/app/board/uXjVMIN-QWE=/) (Confirmed from design)

Fixes 1810: Add quickstart link

---

src/Routes.tsx
src/components/Header/Header.tsx
src/components/QuickStart/QuickStart.test.tsx
src/components/QuickStart/QuickStart.tsx

This is the cherry picked version of [this](https://github.com/content-services/content-sources-frontend/pull/115) PR.

Fixes 1810: Add quickstart link (#115)

---

README.md

Updated the Readme to include an install step for nvm
Check the new step in the Readme do give feedback if you find a better way to say this.

Refs 1918: Update Readme to include install step for nvm

---

deploy/frontend.yaml

This sets the correct insights id within our frontend.yaml

Refs 1737: Update frontend.yaml with correct app ID

---

.github/workflows/build-repo.yml
.github/workflows/content-sources-actions.yml

Try #2
I'll merge once unit tests pass

try another way to get sha

---

.github/workflows/build-repo.yml
.github/workflows/content-sources-actions.yml

refactors actions to have a single job for push, so that the single job builds, tests, and pushes the code for a release.

refactor to use a single push job for build and push

---

.github/workflows/build-repo.yml

Not sure why this wasn't erroring before but is now.

Wrap echo in quotes to avoid error

---

.github/workflows/build-repo.yml

The multiple checkouts was overwriting work

only checkout once and stop uncessary caching

---

.github/workflows/build-repo.yml

specify branch properly

---

.github/workflows/title.yml

adjust title check for multiple issues

---

.github/workflows/stable-merge.yml

Fixes 1737: Update action permission

---

src/Pages/PopularRepositoriesTable/PopularRepositoriesTable.tsx

Refs 2048: Update popular repositories ouiaID's for QE tests

---

package-lock.json
package.json

[postcss] Update postCss

---

.github/dependabot.yml

add dependabot package updates
none

Build: add dependabot

---

src/Pages/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx

Hi, I would like to have an ouiaID for testing the snapshot enable and disable toggle buttons.
TBA

Refs 2405: Add ouiaID for snapshot toggle button

---

.github/workflows/title.yml

previously the regex would allow things like:  "Fixes 123,Fixes 456: Foo"

Build: fix regex allowing multiple fixes

---

src/Pages/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx

Adds a dynamic ouiaId for the snapshot Switch component to be used in tests for identifying state.

Refs 2405: OuidIDSnapshotSwitch

---

src/Pages/PopularRepositoriesTable/PopularRepositoriesTable.test.tsx
src/Pages/PopularRepositoriesTable/PopularRepositoriesTable.tsx

"clicking clear filters button should remove any filters selected from popular repositories table"

Fixes 1172: Clear Filter

---

src/Pages/ContentListTable/ContentListTable.test.tsx
src/Pages/ContentListTable/ContentListTable.tsx

Title case should be sentence case   in snapshot keybab menu.

Fixes 3486: Title case should be sentence case.

---

src/Pages/AdminTaskTable/components/AdminTaskFilters.test.tsx
src/Pages/AdminTaskTable/components/StatusIcon.test.tsx
src/Pages/AdminTaskTable/components/ViewPayloadModal/ViewPayloadModal.test.tsx
src/Pages/ContentListTable/ContentListTable.test.tsx
src/Pages/ContentListTable/ContentListTable.tsx
src/Pages/ContentListTable/components/AddContent/AddContent.test.tsx
src/Pages/ContentListTable/components/ContentListFilters.test.tsx
src/Pages/ContentListTable/components/PackageCount.test.tsx
src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.test.tsx
src/Pages/PopularRepositoriesTable/PopularRepositoriesTable.test.tsx
src/Pages/PopularRepositoriesTable/components/AddRepo.test.tsx
src/components/ConditionalTooltip/ConditionalTooltip.test.tsx
src/components/DeleteKebab/DeleteKebab.test.tsx
src/components/DropdownSelect/DropDownSelect.test.tsx
src/components/EmptyTableState/EmptyTableState.test.tsx
src/components/QuickStart/QuickStart.test.tsx
src/testingHelpers.tsx

Fixes tests using incorrect waitFor pattern
Tests pass and there are no false positives or act warnings

Fixes 3458: fix incorrect waitFor test pattern

---

src/Pages/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx

https://issues.redhat.com/browse/HMS-3607

Fixes 3607: Changed ouaid of snapshot toggle button

---

src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx

This is a 1 character change to fix an inverse value on a page safe within the snapshot modal.

FixSnapshotModalPageSafe

---

src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx

Adds an ouiaID for targeting the row in the snapshotList modal, along with the snapshot UUID in the data-uuid attribute.

Refs 3601: Update packageList data-uuid

---

deploy/frontend.yaml

Refs 2975,2976: Update deploy yaml for templates

---

src/Hooks/useErrorNotification.tsx
src/Hooks/useNotification.tsx
src/Pages/ContentListTable/ContentListTable.tsx
src/Pages/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/ContentListTable/components/AddContent/helpers.ts
src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx
src/Pages/TemplatesTable/components/AddTemplate/steps/DefineContentStep.tsx
src/services/AdminTasks/AdminTaskQueries.ts
src/services/Content/ContentQueries.ts
src/services/Features/FeatureQueries.ts
src/services/Templates/TemplateQueries.ts

Adds static ids to toast alerts.

Fixes 3729: Add static ids to toast alerts.

---

fec.config.js

Build: we no longer live at settings

---

src/components/ZeroState/ZeroState.tsx

Need to locate the description below this title:
Start using Content management now

Fixes 3982: Add ouiaID to locate zerostate description

---

src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx

Adds ouiaID for snapshot package/advisories counts

Adds ouiaID for snapshot package/advisories counts

---

README.md
fec.config.js
package-lock.json
package.json

Updates app to run against stage/prod locally
- `npm start` now runs against the chosen environment (stage/prod - beta/stable) 
- `npm run local` runs against our backend (expects port 8000 but is configurable)

Fixes 3908: Update app to run against stage/prod locally

---

src/App.tsx
src/Pages/ContentListTable/ContentListTable.test.tsx
src/Pages/ContentListTable/ContentListTable.tsx
src/Pages/ContentListTable/components/ContentListFilters.tsx
src/Pages/ContentListTable/components/StatusIcon.tsx
src/Pages/PopularRepositoriesTable/PopularRepositoriesTable.tsx
src/Pages/TemplatesTable/TemplatesTable.test.tsx
src/Pages/TemplatesTable/TemplatesTable.tsx
src/Pages/TemplatesTable/components/TemplateFilters.tsx
src/Routes/Repositories/useRepositoryRoutes.tsx
src/Routes/Templates/useTemplateRoutes.tsx
src/Routes/index.tsx
src/components/DeleteKebab/DeleteKebab.tsx
src/components/NoPermissionsPage/NoPermissionsPage.tsx
src/middleware/AppContext.tsx

Adds support for template permissions to the frontend
Use stage auth, create a user in your org with just  template read role, make sure you can try to create a template.
Try without any template role (but can add repository read), verify you can't access the template page

Refs 4043: adopt template permissions

---

src/Pages/ContentListTable/ContentListTable.tsx

Needs the corresponding backend PR: https://github.com/content-services/content-sources-backend/pull/681
Unblocks the kebab and check boxes for repositories in the Pending status, so that they may be deleted. All kebab options other than delete are still disabled.
1. Create or bulk create repositories.
2. While the status is pending, delete the repositories.

Fixes 3125: allow deletion of pending repository

---

src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx
src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx

- Added a couple checks for the OuiaSafe to hopefully prevent double url input issues on tests.

Fixes 4218: Prevent occasional double url entry on tests

---

.rhcicd/pr_check.sh

we do this on the backend, might fix the build

Build: do not limit pulp resources

---

.rhcicd/pr_check.sh

This will deploy the apps using whatever is in stage which is where PRs are deployed after being merged.
`export REF_ENV="insights-stage"`

Build: pr_check, use insights-stage as ref-env

---

src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/DefineContentStep.tsx
src/components/DropdownMenu/DropdownMenu.tsx

I need some ouiaIDs in the content template form
Will try use the same as those in custom repo modal first.
I'll test manually.

Refs 3419: Add ouiaIDs for template form

---

src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplate.tsx

- Adds the "tab" url param to the template edit modal. 
- This allows the user to save the url and have the specific tab open upon deep link. 
The create modal (the same component) does not share this feature.
- Create a template via the normal flow
- Edit said template, the url param "tab" should update on each navigation change within the modal. 
- Upon deep linking to any location in the modal, the user should be able to land back where they were.

Fixes 4305: Add url params to template edit for routing

---

README.md

readme update to make it more clear about how to patch the hosts file

Build: small readme update

---

src/App.tsx
src/Hooks/usePageSafe.tsx
src/Pages/Repositories/AdminTaskTable/AdminTaskTable.tsx
src/Pages/Repositories/AdminTaskTable/components/AdminTaskFilters.test.tsx
src/Pages/Repositories/AdminTaskTable/components/AdminTaskFilters.tsx
src/Pages/Repositories/AdminTaskTable/components/ViewPayloadModal/ViewPayloadModal.tsx
src/Pages/Repositories/ContentListTable/ContentListTable.tsx
src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContentModal.tsx
src/Pages/Repositories/ContentListTable/components/EditContentModal/EditContentModal.tsx
src/Pages/Repositories/ContentListTable/components/PackageModal/PackageModal.tsx
src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/SnapshotDetailsModal.tsx
src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx
src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx
src/Pages/Templates/TemplatesTable/TemplatesTable.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/CustomRepositoriesStep.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/RedhatRepositoriesStep.tsx
src/services/AdminTasks/AdminTaskApi.ts

This removes all dynamic page safes except for the top level one that listens to the API.

Fixes 4421: Add top level page safe only

---

src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/DefineContentStep.tsx
src/components/DropdownMenu/DropdownMenu.tsx

This was a quick locator request by QE.

Refs 3419: Adds ouia-Ids for the DefineContent Tab

---

src/Pages/Repositories/AdminTaskTable/components/AdminTaskFilters.tsx
src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/Repositories/ContentListTable/components/ContentListFilters.tsx
src/Pages/Repositories/ContentListTable/components/EditContentModal/EditContentForm.tsx
src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/SnapshotSelector.tsx
src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataFilters.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/AddNavigateButton.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/DefineContentStep.tsx
src/Pages/Templates/TemplatesTable/components/TemplateFilters.tsx
src/components/DropdownMenu/DropdownMenu.tsx
src/components/DropdownSelect/DropdownSelect.tsx
src/components/DropdownSelect_Deprecated/DropdownSelect_Deprecated.test.tsx

- Fixes an issue with menu select  
- Labels all deprecated components
- Replaced the following components with the new menuSelect:

Build: Fixes Menu Select

---

src/Pages/Repositories/AdminTaskTable/AdminTaskTable.tsx
src/services/AdminTasks/AdminTaskQueries.ts

##Summary
Admin task polling wasn't working consistently, this change simply applies the same fix that was done for the repositories table on the AdminTask table.
##Testing steps
- Take some action that will produce a task (snapshot, etc..)
- Check the admin task table, if any of the tables statuses appears as "running" or "pending", the api will be polled every 15 seconds; until all are settled.

Fixes 3938: Fix admin task polling

---

src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataFilters.tsx
src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataTab.test.tsx
src/components/SharedTables/AdvisoriesTable/index.tsx

This simply fixes an issue found in IQE testing.
Each table row must be wrapped in a tBody element to be targetable by the IQE component, this pattern is also [recommended](https://www.patternfly.org/components/table#expandable) by patternfly.
Additional Changes: 
- Fixed a bug around clearing the snapshotErrataFilter from empty state.

Build: Fix ExpandableTables

---

src/App.tsx
src/Pages/Repositories/ContentListTable/ContentListTable.test.tsx
src/Pages/Repositories/ContentListTable/ContentListTable.tsx
src/Pages/Repositories/ContentListTable/components/ContentListFilters.test.tsx
src/Pages/Repositories/ContentListTable/components/ContentListFilters.tsx
src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContent.test.tsx
src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataFilters.test.tsx
src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataTab.test.tsx
src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotPackagesTab.test.tsx
src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/CustomRepositoriesStep.tsx
src/middleware/AppContext.tsx
src/services/Content/ContentApi.ts
src/services/Content/ContentQueries.ts

- Updates repositories list API call for use with the incoming upload repositories feature.
- Sanity check, make sure all the things still work?

Refs 4426: Enforce external,upload for custom repositories

---

src/Pages/Templates/TemplatesTable/components/AddTemplate/AddNavigateButton.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplate.tsx

- Fix a small UI bug where the footer would not be present in the review tab.

Fixes 4668: Add a footer wrapper for wizard ui

---

src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataFilters.tsx
src/components/SharedTables/AdvisoriesTable/index.tsx
src/components/SharedTables/PackagesTable/index.tsx

Build:  consoleErrorFix

---

src/Hooks/useArchVersion.tsx
src/Pages/Repositories/ContentListTable/ContentListTable.tsx
src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx
src/Pages/Templates/TemplateDetails/TemplateDetails.tsx
src/Pages/Templates/TemplatesTable/TemplatesTable.tsx

- This attempts to fix an issue with double loading/ui tabs being hidden.

Fixes 4737: Prevent double loading of existing data

---

src/Hooks/useArchVersion.tsx

- Fixes a display bug with ArchVersion that would show "9" instead of "el9".

Build: Fixes a bug with arch/version display

---

src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplate.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/CustomRepositoriesStep.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/DefineContentStep.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/DetailStep.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/RedhatRepositoriesStep.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/ReviewStep.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.tsx

Build: Add OuiaIds for templates

---

src/Pages/Templates/TemplatesTable/TemplatesTable.tsx

Adds the following banner to templates in preparation for release to production.
Banner dismissal is based off of sessionStorage, re-logging should make it re-appear, refreshing will not.
- Look at the banner on the templates page
- Dismiss it, refresh, it should not reappear
- Ensure the navigation to patch from the banner works correctly.

Refs 4776: Add info banner to templates

---

package-lock.json
package.json

This just bumps patternfly to include the changes I made [here](https://github.com/patternfly/patternfly-react/pull/11056) in Patternfly. 
The most obviously effected dropdowns by this change in our application can be found when opening kebabs on tables, and on the snapshot errata list modal > filter dropdowns.
Testing before (Stage) and after this update should be sufficient to see the changes. 
Result should be no jumpiness/auto-scrolling occurs.

Fixes 4746: Jumpiness when clicking menus/dropdowns

---

.tekton/content-sources-frontend-pull-request.yaml
.tekton/content-sources-frontend-push.yaml
renovate.json

Build: update tekton pipelines

---

deploy/frontend.yaml

Adding Selenium requirements to match other plug-ins because of connection errors. 
Tests pass

Build: Add selenium requirements

---

src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.test.tsx
src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx

Fixes 5035: enable uploads in prod preview

---

renovate.json

This reverts commit 1e2c1bf07348c75bad3e312a3da9d3aed74f9f32.

Build: update konflux weekly

---

.github/workflows/title.yml

Build: require full jira id

---

.github/workflows/playwright-actions.yml

Build: fix playwright nightly job run

---

.github/workflows/playwright-actions.yml
.github/workflows/pw-cleanup.yaml
ci-reporter.ts
playwright.config.ts

It is built on top of #423 so disregard the first commit. I want to land that first as it causes issues ATM and this PR might need some iterations :) 
This reporter does following:
- Publish html tests results to github pages
- Publish comment with summary and url link to test results
- When posting comments, previous comment is deleted
Also introducing github action to delete all tests results older than 7 days.

Test: Introduce playwright reporter

---

.github/workflows/playwright-actions.yml

Without this current main is being checked-out.

Test: Checkout PR in PW action

---

src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx
src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataFilters.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/AddNavigateButton.tsx

Right side of the split button is not accessible otherwise.

Include aria-label for split buttons

---

_playwright-tests/UI/Templates.spec.ts
src/Pages/Templates/TemplatesTable/TemplatesTable.test.tsx
src/Pages/Templates/TemplatesTable/TemplatesTable.tsx
src/components/EmptyTableState/EmptyTableState.tsx

This PR makes small UX adjustments to the templates page empty state according to the UX mock-ups.

HMS-5269: small UX changes to template empty state

---

.tekton/content-sources-frontend-pull-request.yaml
.tekton/content-sources-frontend-push.yaml
package.json

Build: Update tekton pipeline to use the correct node version.

---

.github/workflows/playwright-actions.yml
_playwright-tests/UI/SnapshotRepo.spec.ts

Chore: Update CI

---

.github/workflows/playwright-actions.yml

Test: fix setting of CURRENTS_RECORD_KEY

---

_playwright-tests/UI/PopularRepo.spec.ts

The code applies a filter to the search input, checks if the correct filtered result is displayed, and then clears the filter by clicking the "Clear filters" button.
1. Fill the 'Filter by name/url' input with 'EPEL 8 Everything x86_64'.
2. Verify that only one row appears in the table.
3. Ensure the "Clear filters" button is visible.
4. Click the "Clear filters" button to clear the filter.
Jira - [https://issues.redhat.com/browse/HMS-5634](https://issues.redhat.com/browse/HMS-5634)

Adding the clear filtering logic for the Popular repository

---

package.json

Removing node/engine version from package.json which is causing yarn installation issue

---

src/Pages/Templates/TemplateDetails/components/AddSystems/AddSystemModal.tsx

Just fixes an inverse boolean value for QE uses.

HMS-5624: Fix inverse ouiaSafe

---

src/Pages/Repositories/ContentListTable/components/SnapshotListModal/DeleteSnapshotsModal/DeleteSnapshotsModal.tsx
src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx
src/Pages/Templates/TemplateDetails/components/Tables/TemplateRepositoriesTable.tsx
src/Pages/Templates/TemplateDetails/components/Tabs/TemplateSystemsTab.test.tsx
src/Pages/Templates/TemplateDetails/components/Tabs/TemplateSystemsTab.tsx
src/components/SharedTables/PackagesTable/index.tsx

HMS-5268: Template Detail Page - Minor UX Improvements

---

.github/workflowScripts/getBackendBranch.sh
.github/workflows/playwright-actions.yml
_playwright-tests/UI/RedHatRepo.spec.ts

#testwith https://github.com/content-services/content-sources-backend/pull/1026

HMS-5647: switch to code ready repo

---

_playwright-tests/UI/CustomRepoCRUD.spec.ts

Custom Repository CRUD test.
Tests pass.
Based on IQE test in associated Jira.

HMS-5573: Add Repo CRUD test

---

_playwright-tests/UI/IntrospectRepo.spec.ts
_playwright-tests/UI/PopularRepo.spec.ts
_playwright-tests/UI/SnapshotRepo.spec.ts
_playwright-tests/UI/UploadRepo.spec.ts
_playwright-tests/UI/helpers/helpers.ts
_playwright-tests/UI/helpers/navHelpers.ts
yarn.lock

-  Makes tests run in parallel locally only
- Fixes a number of tests that were affecting other tests (namely their cleanup functions
Additional changes: Fixed a number of issues with helpers, namely around not waiting for filters to take effect before continuing.

HMS-5618: Explore parallel tests, fix issues around idempotency.

---

_playwright-tests/UI/SnapshotRepo.spec.ts
_playwright-tests/UI/UploadRepo.spec.ts
_playwright-tests/UI/helpers/helpers.ts

Use same locator as in Custom Repo CRUD test
tests pass

Build: Improve locator

---

.tekton/content-sources-frontend-pull-request.yaml
.tekton/content-sources-frontend-push.yaml

Required tasks by April 1st :)

Build: add required SAST tasks to Konflux pipelines

---

_playwright-tests/UI/GPG_keys.spec.ts

Incorrect error message in GPG key test
GPG key test passes

Fix GPG error message

---

.github/workflows/playwright-actions.yml
_playwright-tests/UI/PopularRepo.spec.ts
_playwright-tests/UI/RedHatRepo.spec.ts
_playwright-tests/UI/Templates.spec.ts
_playwright-tests/UI/UploadRepo.spec.ts
_playwright-tests/UI/helpers/helpers.ts
_playwright-tests/UI/helpers/navHelpers.ts
_playwright-tests/auth.setup.ts
_playwright-tests/helpers/loginHelpers.tsx
fec.config.js
package.json
playwright.config.ts
src/Pages/Templates/TemplatesTable/TemplatesTable.tsx
yarn.lock

This PR tries to fix the CI timeouts and flakiness, also tests and enables parallel test execution.

Test: fix CI flakiness and timeouts

---

.tekton/content-sources-frontend-pull-request.yaml
.tekton/content-sources-frontend-push.yaml

Reverts content-services/content-sources-frontend#518

Build: Revert "Red Hat Konflux purge content-sources-frontend"

---

_playwright-tests/UI/CustomRepoCRUD.spec.ts
_playwright-tests/UI/CustomRepoPagination.spec.ts
_playwright-tests/UI/TemplateCRUD.spec.ts
_playwright-tests/UI/helpers/createRepositories.ts
_playwright-tests/UI/helpers/deleteRepositories.ts
_playwright-tests/UI/helpers/deleteTemplates.ts
_playwright-tests/UI/helpers/helpers.ts
_playwright-tests/UI/helpers/repoHelpers.ts

[HMS-5813] QE: migrate Template CRUD test
peer review

HMS-5813: QE: migrate Template CRUD test

---

.github/workflows/nightly-stage-test-action.yml

The secret is by accident called with 3 Os :)

Test: Use correct secret

---

deploy/frontend.yaml

Build: switch image tag

---

_playwright-tests/UI/RBACUserTest.spec.ts
_playwright-tests/auth.setup.ts
_playwright-tests/helpers/loginHelpers.ts
playwright.config.ts

[HMS-5999](https://issues.redhat.com/browse/HMS-5999#) QE: migrate iqe test_rbac_for_repos
tests pass

HMS-5999: QE migrate iqe test_rbac_for_repos

---

README.md

Copy some steps from the [playwright repo](https://github.com/content-services/content-sources-playwright?tab=readme-ov-file#setup-container-api-for-testing-with-clients) related to running integration tests.
peer review

Build: How to run integration tests

---

_playwright-tests/.cursor/rules/playwright-tests-ts.mdc

This adds cursor rules that specify some best practices and instruct AI tools to use the style guide. This can be used by cursor and code rabbit.

Test: add cursor rules for Playwright tests

---

_playwright-tests/Integration/CanUpdateSystemWithTemplate.spec.ts
_playwright-tests/UI/SnapshotRepo.spec.ts
_playwright-tests/UI/TemplateCRUD.spec.ts
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/DefineContentStep.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/DetailStep.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/RedhatRepositoriesStep.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/ReviewStep.tsx
src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.tsx

Fix various text style issues and make required asterisks red.
Required asterisks were not red because css variable `--pf-v6-c-form__label-required--Color` was not defined. Wrapping FormGroup components in Form component (like in [PF docs](https://www.patternfly.org/components/forms/form/)) solved the issue.
tests passed, peer review

HMS-5263: fix creation wizzard text style issues

---

src/Pages/Repositories/ContentListTable/components/ContentListFilters.tsx

[HMS-8773] Filter on repo status: Change "Pending" to "In progress"
tests pass and one screen capture

HMS-8773: Fix filter on repo status

---

_playwright-tests/UI/RBACUserTest.spec.ts

Add wait-for menu kebab menu to be displayed before checking the menu items
RBAC tests pass

Test: Add wait-for kebab menu

---

.github/workflows/nightly-stage-test-action.yml
.github/workflows/playwright-actions.yml
_playwright-tests/Integration/CanUpdateSystemWithTemplate.spec.ts
_playwright-tests/Integration/LayeredRepoAccess.spec.ts
_playwright-tests/auth.setup.ts
_playwright-tests/helpers/loginHelpers.ts
playwright_example.env

- Adds new users with and without access to layered repos and an integration test to verify access
- Updates CanUpdateSystemWithTemplate to test a layered repo can be included in a template and content can be installed from it on a RHEL9 system

HMS-5095: test for layered product repos

---

_playwright-tests/Integration/AssociatedTemplateCRUD.spec.ts
_playwright-tests/UI/PopularRepo.spec.ts

Negative asserts need additional steps
before asserting it did not occur.
tests pass

Test: Fix unsafe negative asserts
