content-services/content-sources-frontend

src/components/AddContent/AddContent.tsx, src/components/AddContent/helpers.ts, src/components/ContentListTable/ContentListFilters.tsx, src/components/ContentListTable/ContentListTable.tsx, src/components/EditContentModal/EditContentModal.test.tsx, src/components/EditContentModal/EditContentModal.tsx, src/components/EditContentModal/helpers.test.ts, src/components/EditContentModal/helpers.ts, src/services/Content/ContentApi.ts, src/services/Content/ContentQueries.ts
This PR adds the ability to Edit repositories within a list. 
Bulk edit functionality is also complete within the modal should we need it.
We would just need the multi-select boxes/Bulk Edit button/BulkEditAPI, to see that unrequested "feature" complete. 😜 
Additional Changes: 
- Introduced new "single item" UI for both AddContent and EditContent (more streamlined).
- Fixed a bug associated with the textfield on the "name/url" field on filters not being cleared properly
- Fixed a bug associated with the versions not displaying/being stored correctly.
- Fixed a bug associated with AddContent Modal validity after removing items.
=> Fixes 52: Add EditContent Modal

src/components/AddContent/AddContent.test.tsx, src/components/AddContent/AddContent.tsx, src/components/AddContent/helpers.test.ts, src/components/AddContent/helpers.ts, src/components/ContentListTable/ContentListTable.tsx, src/components/ContentListTable/components/StatusIcon.test.tsx, src/components/ContentListTable/components/StatusIcon.tsx, src/components/ContentListTable/components/StatusText.tsx, src/components/EditContentModal/EditContentModal.test.tsx, src/components/EditContentModal/EditContentModal.tsx, src/components/EditContentModal/helpers.test.ts, src/components/EditContentModal/helpers.ts, src/services/Content/ContentApi.ts
- Unhides the GPG key form in the Edit and Add modals. 
- Adds a radio button for the metadata verification option.
I was thinking GPG Key and the verification option should be their own components, but it seems like that would be more than a little disruptive to the current formik stuff. I welcome suggestions there (and anywhere).
=> Fixes 77: add gpg key and verification option

src/components/AddContent/AddContent.test.tsx, src/components/AddContent/AddContent.tsx, src/components/AddContent/helpers.test.ts, src/components/AddContent/helpers.ts, src/components/EditContentModal/EditContentModal.test.tsx, src/components/EditContentModal/EditContentModal.tsx, src/components/Error/ErrorPage.test.tsx, src/components/OptionalTooltip/OptionalTooltip.test.tsx, src/components/OptionalTooltip/OptionalTooltip.tsx, src/services/Content/ContentApi.ts, src/testingHelpers.tsx
This adds validation functionality to be paired with [this backend API ticket](https://github.com/content-services/content-sources-backend/pull/116), allowing the gpg_keys to: 
- Show errors when gpg_key is invalid
- Show errors when Package and metadata verification is set but gpg_key signature does not match.
- Auto-selection of Package and metadata verification option (based on url metadata_verification set to true)
- Auto-selection/disabling of metadata verification option (in case where url metadata_verification set to false).
=> Fixes 208: Add api validation for gpg-keys

src/components/ContentListTable/ContentListTable.tsx
Fixes the above issue, due to the incorrect variable being set.
=> Fixes 274: Status column not sorting correctly

src/components/ContentListTable/components/PackageModal/PackageModal.tsx
Hi
ouiaID to help locate package model once its been opened.
=> Refs 82: Add ouiaID to package modal

src/components/ContentListTable/components/AddContent/helpers.ts, src/services/Content/ContentApi.ts, src/services/Content/ContentQueries.ts
Accompanies this PR: https://github.com/content-services/content-sources-backend/pull/126
Updates the error handling here to work with the error structure defined in said PR.
=> Fixes 182: change api errors to error objects

src/components/ContentListTable/components/PackageCount.test.tsx, src/components/ContentListTable/components/PackageCount.tsx
- Update component to display N/A into the Packages column when the repository state is Invalid.
- Add unit tests for the component.
=> Fixes 263: show N/A for Invalid repositories

src/AppEntry.tsx, src/Routes.tsx, src/components/NoPermissionsPage/NoPermissionsPage.tsx
Fixes a small issue with the redux store being "null" or undefined.
A fix on the main ReduxProvider was already present but there was the use of "Main" component which was imported from the shared front-end components, which needed to be removed as it was using a provider internally.
NOTE TO QE: your main page container id may have changed, I'm not sure if this will affect your existing tests.
=> Fixes 287: Fix for null store error when navigating

src/Pages/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/ContentListTable/components/AddContent/helpers.ts, src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx
This updates the gpgKey input in both the Edit/Add content modals to use a new separate debounce for the gpgKey value via onchange.
=> Fixes 248: Allow gpgKey URL to be updated via onchange

src/services/Content/ContentQueries.ts
Fix for Nan value on pagination component upon deleting an item from the list.
To recreate, simply have a list of greater than 10 items, set the pagination perPage value to 10 and delete 1 item on the first page. 
Looking at the console without this change you should see a react error around Nan values (if using a 3g network connection setting this is also viewable in the pagination component as "Nan")
=> Fixes 318: Fix for Nan value upon deletion error 

src/Pages/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx
removes the .txt requirement
slightly increases max filesize to 8096 (bytes).
Most gpg-keys would be under 4000 but this gives us some headroom for larger keys.
=> Fixes 1116: Can't upload non-txt gpg key

src/Pages/PopularRepositoriesTable/PopularRepositoriesTable.test.tsx, src/Pages/PopularRepositoriesTable/PopularRepositoriesTable.tsx, src/services/Content/ContentQueries.ts
This change makes it so that the Add/Delete options in popular repositories update the list "optimistically", IE before getting a response from the API. 
One should now be able to perform back to back to actions when clicking add or remove (not both) .
FYI QE: To test this make sure to [slow down your network speed ](https://www.browserstack.com/guide/how-to-perform-network-throttling-in-chrome)in the browser.
=> Fixes 1173: Add optimistic updates to popular repositories

deploy/frontend.yaml
Change the navItems[0].href in the Frontend template to match what chrome is expecting to build the All Services menu
=> Change navItem href in frontend YAML

src/Pages/ContentListTable/components/AddContent/helpers.test.ts, src/Pages/ContentListTable/components/AddContent/helpers.ts
A particular gpg key file was found to be above the max upload size (max upload size was 8.096kB, file was 14.96kB).
I increased the limit to 32kB.
1. Create this repo: https://dl.google.com/linux/chrome/rpm/stable/x86_64
2. Uploading this gpg key: https://dl.google.com/linux/linux_signing_key.pub
3. Before the changes it will fail because the file size is too big.
4. Could also test with files above/below the 32kB limit.
=> Refs 1672: increase max gpg upload size

src/Pages/ContentListTable/ContentListTable.tsx, src/Pages/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx, src/Pages/ContentListTable/components/PackageModal/PackageModal.tsx, src/Pages/PopularRepositoriesTable/PopularRepositoriesTable.tsx, src/services/Content/ContentApi.ts, src/services/Content/ContentQueries.ts
This satisfies the first acceptance requirement on the 1473 ticket found [here](https://issues.redhat.com/browse/HMS-1473). 
_- A solution including the use of ouia pagesafe [1] would be  ideal._
Further QE test changes are needed to integrate fully.
=> Fixes 1473: Add data-ouia-page-safe for QA test usage

src/Hooks/useRootPath.tsx, src/Pages/AdminTaskTable/components/ViewPayloadModal/ViewPayloadModal.test.tsx, src/Pages/AdminTaskTable/components/ViewPayloadModal/ViewPayloadModal.tsx, src/Pages/ContentListTable/components/AddContent/AddContent.test.tsx, src/Pages/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/ContentListTable/components/EditContentModal/EditContentModal.test.tsx, src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx, src/Pages/ContentListTable/components/PackageModal/PackageModal.test.tsx, src/Pages/ContentListTable/components/PackageModal/PackageModal.tsx, src/Routes/useTabbedRoutes.tsx
This was causing an issue where root urls of non "insights" would reroute to "settings". 
Expected behaviour is now to inherit the root url, cross domain jumping should not occur.
- Open and close all modals when on the "insights" root address. 
- On close of modal the insights address should remain, and not be replaced by "settings"
=> Fixes 2271: Make url derived from history object for nav

src/Pages/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/ContentListTable/components/AddContent/helpers.test.ts, src/Pages/ContentListTable/components/AddContent/helpers.ts, src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx, src/Pages/ContentListTable/components/EditContentModal/helpers.test.ts, src/Pages/ContentListTable/components/EditContentModal/helpers.ts, src/services/Content/ContentApi.ts
Adds a toggle to the add/edit modals for those orgs/users that have correct permissions. 
(This needs to have [1881](https://github.com/content-services/content-sources-frontend/pull/128) merge first).
- Ensure you have a user/org with the snapshot permissions
- Open the add or edit modals, and see that the user should have snapshots toggled on by default.
- Further testing, for users that do not have access to snapshots, upon create the snapshot variable sent to the API (Check this via the network tab) should default to: snapshot:false
=> Refs 1964: Add snapshot toggle to edit/add modals

.github/workflows/build-repo.yml, .github/workflows/content-sources-actions.yml
For some reason in a workflow, the 'github.sha' variable is changing from the sha of HEAD of the branch, to HEAD of main.  So now we pass the sha via an env variable. 
merge and see if it pushes to the build repo
=> pass sha from build step to push step

src/Pages/ContentListTable/ContentListTable.tsx, src/Pages/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx, src/Pages/ContentListTable/components/EditContentModal/EditContentModal.tsx, src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.test.tsx, src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx, src/Pages/ContentListTable/components/SnapshotListModal/components/ChangedArrows.tsx, src/Routes/useTabbedRoutes.tsx, src/services/Content/ContentApi.ts, src/services/Content/ContentQueries.ts, src/testingHelpers.tsx
Adds the snapshotListModal seen below: 
One can access the above modal through the repository list row kebab seen here: 
If the repository doesn't yet have a snapshot (and snapshots are enabled, IE right after creation) one should see: 
If snapshots are not enabled, the "View Snapshot List" menu option should be hidden.
Additional changes: 
- This ticket incorporates a very small change to satisfy [HMS-2277](https://issues.redhat.com/browse/HMS-2277) until [HMS-1700](https://issues.redhat.com/browse/HMS-1700) can be completed.
Notes: 
- This ticket is dependent on the backend ticket [HMS-2188](https://issues.redhat.com/browse/HMS-2188) which is currently in progress, so merging will need to be delayed until that work has been completed.
- Confirm the above changes are visible and working …
=> Fixes 2189,Fixes 2277: Add snapshotListModal (View only)

src/Pages/AdminTaskTable/AdminTaskTable.tsx, src/services/AdminTasks/AdminTaskQueries.ts
- This is an attempted fix for the duplicate item error being appended in stage. 
- I was unable to replicated the issue locally, but have corrected a few issues in the code around paginating that could be causing this issue. 
- One can check in ephemeral, but this likely needs to be pushed to stage to have its' functionality confirmed.
=> Fixes 2312: Admin tasks interface append results

src/Pages/ContentListTable/components/AddContent/helpers.test.ts, src/Pages/ContentListTable/components/AddContent/helpers.ts, src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx
This updates the add/edit modals with the following functionality around validation: 
For the add modal: 
- The controller will focus on url errors first, even if the gpg key has the wrong value as it is dependant on the URL for validation.
- Only mandatory fields have a green check mark and the input gpg key box will only have a red mark if we enter the wrong value.
- if the name and gpgkey both have errors they will both show a red check as they are not hierarchally dependent.
For the Edit modal: 
- Validation will only show green checkmarks (showing updated values) if there are no errors showing, and when the validation API returns clear. 
- If an error is present, no checkmarks will show, forcing the user to focus on the error before confirming any other changes. 
- The same error …
=> Fixes 1700: Update edit/add modal checkmark functionality

.github/workflows/stable-merge.yml
Adds a github script as a work-around so that we will have two branches, main/main-stable (effectively copied but different hashes).
- None unfortunately
=> Fixes 1737: Add stable merge.yml

src/Pages/ContentListTable/ContentListTable.test.tsx, src/Pages/ContentListTable/ContentListTable.tsx, src/Pages/ContentListTable/components/AddContent/helpers.ts, src/testingHelpers.tsx
- Added "Snapshot" related info to the repositories list table (sketch reference [here](https://www.sketch.com/s/b55e75a8-9a53-4eb0-989e-aad208521aba/a/VEkGYmq))
- Displays "No snapshot yet" if there are no snapshots, otherwise displays "Last snapshot (creation time of last snapshot) Changes: " with # of additions and # of removals using the ChangedArrows component
- Displays nothing if feature not enabled
- Updated tests
- Enable snapshot feature, snapshot info should be displayed
- When feature is disabled, it should look as before
- Depends on [this PR](https://github.com/content-services/content-sources-backend/pull/457)
=> Fixes 2190: added snapshot info to content list table

src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.test.tsx, src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx, src/Pages/ContentListTable/components/SnapshotListModal/components/RepoConfig.tsx, src/services/Content/ContentApi.ts, src/services/Content/ContentQueries.ts, src/testingHelpers.tsx
Adds a new column to the snapshot list modal that allows the user to either copy or download the repo config file for the snapshot.
1. Create a repository with snapshotting enabled
2. Click "view all snapshots" on the kebab
3. Under the "Config" tab, try clicking the copy icon (to copy) and the download icon (to download)
=> Fixes 2617: copy/download repo config from snapshot list

src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx
Typically we want newest snapshots first, so descending order makes more sense
Look at snapshot list when there are more than 1, see newest first
=> Fixes 2935: sort snapshots using desc

src/Pages/ContentListTable/ContentListTable.tsx, src/Pages/ContentListTable/components/ContentListFilters.tsx
- Makes it so that Red hat repositories will not be accessible without feature.snapshot permissions.
- Turn off snapshotting in the backend config
- Run the ui, the toggle button for redhat repositories should no longer be accessible
- Deeplinking to content?origin=redhat will also not work.
=> Fixes 3274: Hides RH repo when snapshots not enabled

src/Routes/useTabbedRoutes.tsx
Fixes snapshot modal route to not require admin tasks to be enabled
- Disable admin tasks feature in the backend
- Snapshot list modal should open normally
=> Fixes 3518: fix routing conditional for snapshot modal

src/Pages/ContentListTable/ContentListTable.test.tsx, src/Pages/ContentListTable/ContentListTable.tsx, src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx, src/testingHelpers.tsx
Errata delta in pulp is unreliable, as ordering of things seem to count as a new errata, throwing the counts off.  For now we will just show package change count.
Snapshot a repo with package and errata (https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/) , view delta on repos table and snapshot list.  Delta count should match package count.
=> Fixes 3472: change snapshot delta to only use package count

src/middleware/AppContext.tsx
Hides snapshotting in prod stable
Turn on snapshotting in the backend:
```
features:
snapshots:
enabled: true
accounts: 
users: 
```
launch frontend with stage stable/beta, prod stable/beta.
It should not be available in prod stable, but should be elsewhere.
=> Fixes 3630: hide snapshotting in prod stable

src/Pages/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx
- In the add/edit repository modals, when a user rapidly toggles the switches to enable/disable snapshots or modularity filtering, this triggers an infinite loading state of the Save button and it never becomes clickable
- This change fixes that 
- Toggle the snapshot or modularity filtering switches quickly, the Save button should become clickable
=> Fixes 3608: switches in repo modals cause infinite loading 

src/Pages/ContentListTable/ContentListTable.tsx, src/Pages/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx, src/Pages/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx, src/middleware/AppContext.tsx
- We can't sort on the combined status ([PR here](https://github.com/content-services/content-sources-backend/pull/587)) as it's not stored in the db, so this change disables sorting on the status column in the ContentListTable
- Status column should not be sortable
=> Refs 3488: disable sorting on status

src/services/Content/ContentApi.ts, src/services/Content/ContentQueries.ts
adapts the frontend to the changes here: https://github.com/content-services/content-sources-backend/pull/596
Test with backend and see that fetching snapshot config file works and that you can create a content template without error
=> Refs 3720: Migrate to new snapshot apis

src/Pages/ContentListTable/ContentListTable.tsx
Introduced a bug that prevented sorting on the repositories list view table 3 days ago. 
This fixes it.
=> MergeConflictSortFix

src/App.tsx, src/Routes/index.tsx, src/components/ZeroState/ZeroState.tsx, src/middleware/AppContext.tsx, src/services/Content/ContentQueries.ts
Adds a zero state for when a user has no custom repositories added yet. 
This is the current zero state:
- When a user enters the app and has no custom repositories, they should see the zero state
- Clicking the `Add custom repositories` button from the zero state component should route them to the modal to add a repository
- Once they add a repository, they should not see the zero state once they leave and visit the app again. In that case they should instead be routed to the Repositories page 
- If a user enters the modal to add a repository from the zero state, and closes the modal before adding a repository, the empty repository table state should be shown. If they refresh the page, they should see the zero state again. 
- If a user has repositories and then deletes them all, upon …
=> Fixes 2726: Custom repositories missing zero state

src/Pages/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.test.tsx, src/Pages/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.tsx, src/services/Content/ContentApi.ts, src/testingHelpers.tsx
Adapts frontend for https://github.com/content-services/content-sources-backend/pull/625
1. make repos-import
2. create a repo with snapshotting (something like  https://jlsherrill.fedorapeople.org/fake-repos/needed-errata/)
3. navigate to /insights/content/templates/    
4. create a template and set the date to yesterday
5. you should see a warning pop up saying something about no snapshot availalbe
6. select todays date, the warning should go away
=> Refs 3902: Use new format for snapshot by date

src/Pages/ContentListTable/ContentListTable.tsx, src/Pages/ContentListTable/components/EditContentModal/helpers.test.ts, src/Pages/ContentListTable/components/StatusIcon.test.tsx, src/Pages/ContentListTable/components/StatusIcon.tsx, src/services/Content/ContentApi.ts, src/services/Content/ContentQueries.ts, src/testingHelpers.tsx
- Updates ContentListTable's StatusIcon to use the unified status for introspection and snapshotting
- Needs to be tested with this [backend PR](https://github.com/content-services/content-sources-backend/pull/587)
- Introspect and snapshot a few repositories 
- The repository's unified status should be reflected in the UI instead of the last introspection status
- If a repository's status is In progress and the snapshot task is running, you should see a tooltip on the status with content `Repository snapshot in progress`. Otherwise if the status is pending you should see `Repository is being introspected`
- If a repository's status is Invalid and there is a snapshot error, you should see that error in the tooltip. Otherwise, if there's an introspection error, you should see that one. If …
=> Fixes 3473: snapshot status update

src/services/Content/ContentApi.ts
Fixes sorting by date in SnapshotList modal
- Create a repo and snapshot it a couple times, then go to SnapshotList modal (click View all snapshots)
- Sorting on the date column should work, defaults to descending order
=> Fixes 3812: sorting snapshots by date appears broken

src/Pages/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/ContentListTable/components/AddContent/helpers.test.ts, src/Pages/ContentListTable/components/AddContent/helpers.ts, src/Pages/ContentListTable/components/EditContentModal/EditContentForm.tsx, src/Pages/ContentListTable/components/EditContentModal/helpers.test.ts, src/Pages/ContentListTable/components/EditContentModal/helpers.ts
Fixes the modularity filtering toggle to default to ON if modularity filtering is enabled (default behavior) in repo create / edit modals
- Add a repo with default modularity filtering behavior (toggle should be ON, label text should display `Modularity filtering enabled`, and should set `module_hotfixes = false` on the repository)
- Edit the repo to disable modularity filtering by toggling to OFF (label text should display `Modularity filtering disabled` and set `module_hotfixes = true`)
=> Fixes 3953: modularity filtering option is not clear

src/Pages/TemplatesTable/components/AddTemplate/AddTemplate.tsx, src/helpers.ts
Fixes the template date format sent in the create / edit template requests. This was inadvertently updated in the last commit.
- Creating and editing a template should not fail
=> Fixes 4046: template date formatted incorrectly

src/Pages/AdminTaskTable/AdminTaskTable.tsx
When sorting by status, the frontend was actually requesting the API to sort by started_at
1. Get a mix of task statuses by snapshotting a few repositories.
2. Go to the admin tasks tab and try the status filter
=> Fixes 3846: fix admin tasks sort_by status

src/AppEntry.tsx, src/Pages/ContentListTable/ContentListTable.tsx, src/index.scss, src/services/Content/ContentQueries.ts
- Fixes a bug found with polling when navigating: When navigating to other pages/tabs and returning, polling would stop.  Now polling will continue regardless of page refresh, tab change, etc.. in cases where polling is needed (if there are pending states being returned).
- Patternfly has a known bug with their bottom-navigation Pagination component, I have applied css to temporarily fix this until it's patched
- Fixed a couple recurring console warns around the Th requiring an aria-label
- Try before, try after.
=> Fixes 4105: Polling, css, console warn bugfix

src/Pages/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataTab.tsx, src/components/SharedTables/AdvisoriesTable/index.tsx, src/services/Content/ContentApi.ts, src/services/Content/ContentQueries.ts
- Enables sorting on snapshot errata by issued_date, type, and severity
- Dependent on these PRs: https://github.com/content-services/tang/pull/9, https://github.com/content-services/content-sources-backend/pull/673
- Create a repository and let it snapshot
- View the snapshot errata by clicking View all snapshots in the kebab and then on the Errata count on the snapshot details page
- The Type, Severity, and Publish date (issued date) columns should be sortable
- Should default to sorting by Publish date descending
=> Fixes 4009: snapshot errata should be sortable

src/components/ZeroState/ZeroState.tsx
Changed from this:
to this:
Navigation on button click now goes to the repositories list page instead of the Add modal.
=> Fixes 3958: Zerostate update

src/services/Templates/TemplateQueries.ts
Adds an invalidation of the template fetched to the edit template query to always pull in the latest template data to the edit modal
- Add a repo, let it snapshot, and create a template with that repo's snapshot
- Edit the template date in the edit modal and save it
- Open the edit modal again and the date should be correct
- The template name should be editable once this [PR](https://github.com/content-services/content-sources-backend/pull/694) is merged in
=> Fixes 4242: attempting to edit a template changes the date

src/Pages/Repositories/AdminTaskTable/AdminTaskTable.tsx, src/Pages/Repositories/AdminTaskTable/components/AdminTaskFilters.test.tsx, src/Pages/Repositories/AdminTaskTable/components/AdminTaskFilters.tsx, src/services/AdminTasks/AdminTaskApi.ts
Adds a type filter to the admin tasks tab
1. Checkout this backend PR: https://github.com/content-services/content-sources-backend/pull/710
2. Create or delete some repos or templates to create some tasks
3. Navigate to the admin tasks tab and use the Type filter
=> Fixes 4133: add types filter to admin tasks list

src/Pages/Repositories/ContentListTable/ContentListTable.tsx, src/Pages/Repositories/ContentListTable/components/ContentListFilters.test.tsx, src/Pages/Repositories/ContentListTable/components/ContentListFilters.tsx, src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContent.test.tsx, src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContentModal.tsx, src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.test.tsx, src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx, src/Pages/Templates/TemplatesTable/TemplatesTable.tsx, src/Pages/Templates/TemplatesTable/components/TemplateFilters.test.tsx, src/Pages/Templates/TemplatesTable/components/TemplateFilters.tsx, src/components/DeleteKebab/DeleteKebab.test.tsx, src/components/DeleteKebab/DeleteKebab.tsx, src/helpers.ts, src/services/Templates/TemplateApi.ts, src/testingHelpers.tsx
- Adds a confirmation modal when deleting one or many repositories
- If a repo is associated with any templates, the modal shows a warning message and which templates are associated with it
- Add a few custom and popular repositories, let them snapshot, and create some templates from those repositories' snapshots
- Deleting a custom or popular repository via the delete kebab or Popular Repositories tab should route to the confirmation modal. Clicking Remove in the modal should remove this repository
- Bulk deletion of repositories should route to the confirmation modal and show a table of the repositories selected to delete. Clicking Remove in the modal should remove each repository
- If a repository has associated templates, a warning message and the list of templates should be shown in …
=> Fixes 3794,4173,4210: delete confirmation modal for repos

src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.test.tsx, src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.test.tsx, src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx, src/Pages/Repositories/PopularRepositoriesTable/components/AddRepo.test.tsx, src/Pages/Repositories/PopularRepositoriesTable/components/AddRepo.tsx, src/middleware/AppContext.tsx
- Exposes snapshotting in prod stable
- Temporarily disables snapshotting by default for custom and popular repos in prod stable
When running the frontend on prod->stable:
- Snapshotting should be turned on
- When adding a custom repo, snapshot creation should default to disabled (see screenshot below)
- The top-level add / batch add button for popular repositories should add repositories with snapshotting disabled
- The hidden button in the add / batch add dropdown should show an option to "Add with snapshotting", which should add these repositories with snapshotting enabled (see screenshots below)
=> Fixes 4257: expose/disable snaps by default in prod stable

src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContentModal.tsx
Fixes bug in the delete confirmation modal where if bulk deleting multiple repos that are associated with more than 3 templates, expanding one repo's list of associated templates would expand all lists
- Add 2 repos, let them snapshot, and create at least 3 templates with each repo
- Try to bulk delete the repos in the UI and click `and X more` in the delete confirmation modal. It should only expand the list of templates selected
=> Fixes 4327: expanding one list opens all lists

src/Pages/Repositories/ContentListTable/ContentListTable.test.tsx, src/Pages/Repositories/ContentListTable/ContentListTable.tsx, src/Pages/Repositories/ContentListTable/components/StatusIcon.test.tsx, src/Pages/Repositories/ContentListTable/components/StatusIcon.tsx, src/services/Content/ContentQueries.ts
- Changes Trigger snapshot action to kick off both introspection and snapshot tasks
- Only shows the Introspect now action if a repo doesn't have snapshotting enabled
- Errors are labeled as coming from either introspection or snapshot
- Adds fix to allow users to see their previous snapshots if they exist even if the repo has snapshotting disabled
- Create 2 repositories, one with snapshotting enabled and one with it disabled. You should still see Introspect now as an action in the kebab for the snapshot-disabled repo, but should not see it for the snapshot-enabled repo
- Clicking Trigger snapshot for the snapshot-enabled repo should kick off both introspection and snapshotting. You can verify this in the backend logs or wait to see the Last Introspection time change in the UI
- If there …
=> Fixes 4392,4444: improve recovery from failed snapshot

src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContent.test.tsx, src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContentModal.tsx, src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.test.tsx, src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx, src/Routes/Repositories/useRepositoryRoutes.tsx, src/components/DeleteKebab/DeleteKebab.tsx
This fixes the routing issues when trying to removing popular repos by adding a delete route specific to popular repos. 
- When clicking Remove on one popular repository, this should route to the delete modal and show the selected repo. This is currently broken in stage preview and prod preview and returns a 404. Make sure to test this in preview environments (for devs, npm run local > stage > beta or npm run local > prod > beta)
- When trying to delete popular repos by bulk selecting, this should route to the delete modal and show the selected repos
- If a repo has associated templates, clicking on the template should route to the custom repos step in the template modal
- Also fixes the positioning of the expanded content (list of templates) in the delete modal if a repo is associated …
=> Fixes 4475,4438: routing issues when deleting popular repos

src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.test.tsx, src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx, src/Pages/Repositories/PopularRepositoriesTable/components/AddRepo.test.tsx, src/Pages/Repositories/PopularRepositoriesTable/components/AddRepo.tsx
In prod-beta, snapshotting should not be disabled by default. This fixes that behavior 
- In prod-beta, snapshotting should be turned on and enabled by default when adding a custom repository
- The button behavior for adding popular repositories should be the same as it is in stage (split button should be Add > Add without snapshotting instead of Add > Add with snapshotting)
=> Fixes 4474: fix snapshot behavior in prod-beta

src/Pages/Repositories/ContentListTable/ContentListTable.tsx, src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContentModal.tsx, src/Pages/Repositories/ContentListTable/components/EditContentModal/EditContentModal.tsx, src/Pages/Repositories/ContentListTable/components/PackageModal/PackageModal.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/SnapshotDetailsModal.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplate.tsx
- Fixes an issue where modals were redirecting on close, causing a rerender of the root node > clearing filters and component state.
- Set a filter on the repositories page, open and close any modal, the filter should remain.
=> Fixes 4223: Ensure modals do not cause redirect on close

src/Pages/Repositories/AdminTaskTable/components/ViewPayloadModal/ViewPayloadModal.tsx, src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContentModal.tsx, src/Pages/Repositories/RepositoryLayout.tsx, src/Routes/constants.ts, src/Routes/index.tsx
- Rewrote the routing for the repositories app, will hopefully be much easier for others to work on/add to.
- Changed "content/popular-repositories" to "content/repositories/popular".
- Ensure all routing still works as expected for the repositories app. 
- Make sure all redirects are working as expected (/content/asdf or /content/repositories/asdf, etc..)
=> Fixes 4524: Fix menu routing for popular repos

README.md
Add missing setup step `npm run build` to the README getting started section and add a mention of the VPN requirement for the `npm run local|start`.
=> Build: add steps to readme

src/Pages/Templates/TemplateDetails/components/Tabs/TemplateErrataTab.test.tsx, src/Pages/Templates/TemplatesTable/TemplatesTable.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplateContext.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.test.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.tsx, src/Pages/Templates/TemplatesTable/components/templateHelpers.test.ts, src/Pages/Templates/TemplatesTable/components/templateHelpers.ts, src/helpers.ts
This PR fixes the zero date format issues in the `TemplateTable` found [here](https://issues.redhat.com/browse/HMS-4297). Also adds a tooltip displaying the snapshot date in the UTC format (not converted to local, which the date in the table is) as @swadeley suggested.
Also has a [sibling back-end PR](https://github.com/content-services/content-sources-backend/pull/785) which makes the template API output all dates as UTC.
Create a template with the zeroed date and `use_latest=false`.
```bash
http :8000/api/content-sources/v1.0/templates/ "$( ./scripts/header.sh 18064594 1111)" arch='x86_64' version='9' repository_uuids:='[]' name='test zero' use_latest:=false
```
Verify the date in the table is displayed correctly as `01 Jan 0001` and doesn't change even when changing timezones of the …
=> Refs 4297: fix zero date format, add UTC tooltip

src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx
This just fixes a locator typo for the snapshot advisory count button
=> Refs 3483: fix locator typo

src/Pages/Templates/TemplateDetails/components/TemplateActionDropdown.tsx, src/Pages/Templates/TemplatesTable/TemplatesTable.test.tsx, src/Pages/Templates/TemplatesTable/TemplatesTable.tsx, src/Pages/Templates/TemplatesTable/components/DeleteTemplateModal.test.tsx, src/Pages/Templates/TemplatesTable/components/DeleteTemplateModal.tsx, src/Routes/constants.ts, src/Routes/index.tsx
Adds a delete modal for templates when deleting a template:
* via the kabab menu in the templates list
*  via the actions drop down in the templates detail
When there is a system assigned:
When there are no systems assigned:
=> Fixes 4624: add template delete modal

src/components/ZeroState/ZeroState.tsx
- Adds the following panel with two cards to the zerostate view.
- Feedback on copy desired and welcome! (@swadeley)
- Click the buttons for each card, ensure navigation works as intended.
=> Fixes 3459: Update zero state component

src/Pages/Templates/TemplateDetails/components/Tables/TemplateRepositoriesTable.tsx, src/Pages/Templates/TemplateDetails/components/Tabs/TemplateRepositoriesTab.test.tsx, src/Pages/Templates/TemplateDetails/components/Tabs/TemplateRepositoriesTab.tsx, src/Pages/Templates/TemplateDetails/components/TemplateDetailsTabs.test.tsx, src/Pages/Templates/TemplateDetails/components/TemplateDetailsTabs.tsx, src/Routes/index.tsx, src/services/Content/ContentApi.ts, src/services/Templates/TemplateApi.ts, src/services/Templates/TemplateQueries.ts, src/testingHelpers.tsx
This PR adds a new "Repositories" tab in the template detail view, which displays the snapshots of repositories contained in that template. With links to the repositories and it's packages and errata. 
\
1. Create two templates one with some custom repos in it and one without any.
2. Verify that when viewing the empty template there is a "No repositories" message and when you search the message changes to no repos found.
3. Verify that the template with custom repos has the snapshots for those repos listed in the new tab. You should also be able to filter them by the repo name and order by the repo name or the snapshot date. Also the links should all navigate to the right destinations as per the [issue description](https://issues.redhat.com/browse/HMS-4572).
=> Fixes 4572: list snapshots/repositories in template detail

src/Pages/Templates/TemplatesTable/TemplatesTable.tsx
- This fixes the broken sort variables on the template table
- Date/description no longer can be sorted (API does not permit this action)
=> Fixes 4736: Broken template sorting

src/App.tsx, src/Hooks/useIsEphemeralEnv.tsx, src/Pages/Templates/TemplateDetails/components/Tabs/TemplateSystemsTab.test.tsx, src/Pages/Templates/TemplateDetails/components/Tabs/TemplateSystemsTab.tsx, src/Pages/Templates/TemplateDetails/components/TemplateActionDropdown.test.tsx, src/Pages/Templates/TemplateDetails/components/TemplateActionDropdown.tsx, src/Pages/Templates/TemplatesTable/TemplatesTable.tsx, src/Pages/Templates/TemplatesTable/components/TemplateFilters.tsx, src/Routes/index.tsx, src/middleware/AppContext.tsx, src/services/Subscriptions/SubscriptionApi.ts, src/services/Subscriptions/SubscriptionQueries.ts
This PR introduces a subscription check for disabling template add/edit actions (and routes) for users that don't have a valid RHEL subscription.
Verify that when signed in with a user that has a valid subscription everything works fine. \
And when signed in with a user that doesn't (the future API implementation determines that) these things are true:
- _Add Content Template_ is disabled on the template page.
- The kebab menu is disabled for each item in the template table.
- The actions select in the _Template Detail_ view is disabled.
- You can't access the add/edit template modal by visiting the URL for it.
=> Fixes 4526: added subscription check in templates

README.md, package.json, src/Pages/Templates/TemplatesTable/TemplatesTable.test.tsx, src/Pages/Templates/TemplatesTable/TemplatesTable.tsx, src/Pages/Templates/TemplatesTable/components/StatusIcon.test.tsx, src/Pages/Templates/TemplatesTable/components/StatusIcon.tsx, src/services/Templates/TemplateApi.ts, src/services/Templates/TemplateQueries.ts, src/testingHelpers.tsx
- Adds a status column to the template list page
- Displays any errors if there's an Invalid status
- Also adds 2 commands to run the app against stage or prod (`npm run start:stage` and `npm run start:prod`) without needing to select from a menu - thank you @marusak for the suggestion!
1. Add a custom and RH repository, let them snapshot, and create a template using latest content. The template status in the UI should change to In progress and then Valid once the update-template-content task completes.
2. Edit the custom repo URL used in the template to create a new snapshot. Once the snapshot finishes, stop the server and remove the pulp URL. Restart the server. The template status should now be Invalid and display the error from the update-latest-snapshot task when clicking on it.
3. …
=> Fixes 4670: show last error and status for templates

src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.tsx
- Updates template request to format the date since [this PR](https://github.com/content-services/content-sources-backend/pull/839) removes support for YYYY-MM-DD date formats
1. Run the backend on the main branch
2. Create a template and set a snapshot date, this should still work as expected
3. Check out [this PR](https://github.com/content-services/content-sources-backend/pull/839) and do the same. This should also work
=> Refs 4151: remove support for YYYY-MM-DD date formats

src/Pages/Templates/TemplateDetails/components/AddSystems/AddSystemModal.test.tsx, src/Pages/Templates/TemplateDetails/components/AddSystems/AddSystemModal.tsx, src/services/Templates/TemplateApi.ts, src/services/Templates/TemplateQueries.ts, src/testingHelpers.tsx
- Checks if environment is created (`rhsm_environment_created == true`) before allowing user to assign the template to a system
- Displays an error if the environment has not been created but the template's update task has finished
- (You will see some unintended behavior here when adding multiple templates until this [PR](https://github.com/content-services/content-sources-backend/pull/866) is merged)
Since this depends on Patch's API, this needs to be tested on stage (`npm run start:stage`). You will also need to have [registered](https://github.com/content-services/content-sources-backend/blob/main/docs/register_client.md#registering-a-subscription-manager-client-to-stage-environment) at least one system on stage. This also cannot be tested in ephemeral as the task that sets the …
=> Fixes 4826: prevent adding systems if env not yet created

src/services/Content/ContentQueries.ts
Adds an invalidation of the content list to the introspect query. Without this we may see cached results in the UI after a successful introspection.
1. Create 2 repos of type Introspect only
2. Introspect one of the repos via the action in the kebab. Once the status becomes valid, you should see the Last Introspection time for both repos updated
=> Fixes 4918: missing invalidation on introspection

src/components/ZeroState/ZeroState.tsx
Catch up with other zero states, see https://github.com/RedHatInsights/insights-dashboard/blob/5bf9f1bdbc7720de71dff7dc5a11ffb60b0b2b6b/src/PresentationalComponents/ZeroState/ZeroStateBanner.js#L111
Before:
Now:
Other places:
=> Fixes 4913: Update zero-state button to PF5

src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx
- Adds hover text pop up in Edit rpm upload modal
- Open edit modal for a upload repository, hover to see the new messaging.
=> Fixes 4763: Add hover text pop up in Edit rpm upload modal

.tekton/content-sources-frontend-pull-request.yaml, .tekton/content-sources-frontend-push.yaml, ci.sh
* make the build-container step dependent on the  build-dockerfile step
* adds a workaround to delete duplicate source code in the tree
=> Build: add konflux workaround

eslint.config.mjs, src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx, src/Pages/Templates/TemplatesTable/TemplatesTable.tsx, src/components/Header/Header.tsx
Removes a banner that is no longer needed.
- Without the PR, there is a banner in templates
- After the PR, no banner.
=> HMS-5203: Remove template patch banner

.github/dependabot.yml
This makes dependabot ignore major versions of a few modules, as it isn't capable of making the upgrade without assistance.
=> Build: Update dependabot

src/components/SharedTables/AdvisoriesTable/index.tsx
This PR fixes a bug where errata are duplicated in the advisories tab in the template detail. 
Before:
After:
- In stage navigate to a template and verify the errata aren't duplicated.
=> HMS-5187: fix duplicate errata in template detail

src/Hooks/useIsEphemeralEnv.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx, src/Pages/Repositories/ContentListTable/components/UploadContent/UploadContent.tsx, src/Pages/Repositories/ContentListTable/components/UploadContent/components/FileUploader.tsx, src/Pages/Repositories/ContentListTable/components/UploadContent/components/UploadStatusItem.tsx, src/Pages/Repositories/ContentListTable/components/UploadContent/components/helpers.tsx, src/services/Content/ContentApi.ts, src/services/Content/ContentQueries.ts, src/services/Subscriptions/SubscriptionQueries.ts
Adds support for resumable downloads.
Can test with [this](https://github.com/content-services/content-sources-backend/pull/918) back-end PR.
- Create an upoad repository.
- Select an item for upload, allow it to upload around halfway and then immediately hit refresh.
- After refresh, choose the same item, you should be able to see that item continue where you left off.
- After this item has been completed, upload it, and create another upload repository.
- Choose the same file, it should instantly be available.
=> HMS-5126: Add support for resume/skip uploads

src/App.tsx, src/Routes/index.tsx
Tiny change to ensure that zerostate is checked on redirect from /content/ /content  <  in these two default cases.
=> HMS-5226: Fix redirect for zerostate

src/Pages/Templates/TemplateDetails/TemplateDetails.test.tsx, src/Pages/Templates/TemplateDetails/TemplateDetails.tsx, src/Pages/Templates/TemplateDetails/components/UseTemplate/AnsibleTab.tsx, src/Pages/Templates/TemplateDetails/components/UseTemplate/CurlTab.tsx, src/Pages/Templates/TemplateDetails/components/UseTemplate/InsightsTab.tsx, src/Pages/Templates/TemplateDetails/components/UseTemplate/UseTemplateModal.tsx
Adds a "use template" button in the top left of the template details page that opens a modal with different sets of instructions on how to use templates.
=> HMS-5024: add use template modal

src/Pages/Repositories/ContentListTable/ContentListTable.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx, src/components/SharedTables/AdvisoriesTable/index.tsx, src/middleware/AppContext.tsx
Small change to update permissions to allow read-only users to view snapshots
- Get a read -only user, check before and after this change. 
- With this change they should now be permitted to look at the snapshotList within the kebab for each repository.
=> HMS-5197: Fixes List snapshot being disabled for read only users

src/Pages/Repositories/ContentListTable/ContentListTable.tsx
Kebab no longer needs to be disabled on the content list page. 
This fix is the result of a failing test! Huzzah!
=> Fixes kebab being disabled on content list page

src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotListModal/components/LatestRepoConfig.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotListModal/components/RepoConfig.tsx
This adds the latest snapshot uuid as a data-uuid on the latest snapshot config buttons so we can target that in IQE tests ([HMS-4890](https://issues.redhat.com/browse/HMS-4890)) 
`data-uuid` should be set to the latest snapshot uuid on the copy and download buttons for the latest snapshot config
=> Build: add data-uuid to latest snap config

src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplate.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplateContext.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.test.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.tsx, src/helpers.ts
This PR fixes the existing problems with the date picker (weird input behavior, problematic validation and it makes the "next" action dependent on the input) in our template wizard and also implements proposed UX changes.
1. Verify the date picker works correctly/better than before. (i.e. no "Invalid Date" strings, you can type out the date normally)
2. Check that the warning and the listed repos are showing up correctly. (i.e. all repos that have all snapshots past the selected date are showing up only when they should)
3. Make sure the "Next" button doesn't allow you to go further if the "Use up to specific date" option is selected and the date isn't valid.
=> HMS-5267: template wizard date picker fix, UX changes

playwright_example.env
Explain when to use proxy for running playwright tests
```
:~/content-sources-frontend$ grep -r PROXY playwright_example.env 
PROXY="" # Set this if running directly against stage (not using "yarn local")
```
=> Add line about use of proxy when running playwright tests

.github/workflows/title.yml
Same as https://github.com/content-services/content-sources-backend/pull/966
=> Build: allow for prs with Test prefix

playwright.config.ts
Adjusts the `testIdAttribute` in the PW config so we can also target elements by their existing OUIA ID if they have one (ref: https://playwright.dev/docs/api/class-testoptions#test-options-test-id-attribute)
Tested in this [PR](https://github.com/content-services/content-sources-frontend/pull/424/files#diff-2e9a283d227e8009621a499930fe4cc45b364803fc6967adb0c1c644455d79acR10), you could also adjust an existing test case to target an element by OUIA ID to verify
=> Test: allow targeting of elements by OUIA ID

.github/workflows/playwright-actions.yml
There is not any value in doing this. It makes these tests slower, more complex and opens it up to being flaky or broken. Let's keep it simple and only do things, that are bringing real value.
=> Tests: Don't run API tests in frontend tests

_playwright-tests/UI/CustomRepo.spec.ts, _playwright-tests/UI/Templates.spec.ts, _playwright-tests/UI/UploadRepo.spec.ts, _playwright-tests/auth.setup.ts
This PR is a small fix that changes the so far used describe method for test suites to one that comes from `playwright` rather then from `node:test`. This will enable integration with playwright adapters and minimize imports.
- Verify that tests run as expected.
- If you are using playwright through some sort of plugin/extension, you should now have option to run the whole describe with one action. (i.e.: if you are using VS Code, you will have a play/run button next to the describe 🎉 )
=> Test: fix describe usage, use playwright test describe

.github/workflows/playwright-actions.yml
This would allow us to test changes to `playwright-actions.yml`
Note: This will only allow us to trigger it manually. I have sneaky suspicion that it won't work yet as we check for some PR specific items. I will then debug it and condition these things only for triggers coming from PRs.
=> Test: Allow triggering pw manually

.github/workflows/playwright-actions.yml
- Adds action to add the cdn cert for RH repos to the backend config
- Tested in this [PR](https://github.com/content-services/content-sources-frontend/pull/424)
=> Test: add cdn cert

_playwright-tests/UI/RedHatRepo.spec.ts
- Depends on this [PR](https://github.com/content-services/content-sources-frontend/pull/440) adding in the CDN cert
- Adds test to validate the imported RH repo exists, has a status of "Valid", and has at least one snapshot
- Tests pass, all criteria in linked issue is covered
=> HMS-5426: add PW test for RH repos

_playwright-tests/UI/IntrospectRepo.spec.ts, _playwright-tests/UI/helpers/deleteRepositories.ts, _playwright-tests/UI/helpers/helpers.ts, playwright.config.ts
This PR adds PW tests for introspect only repositories. Also adds new helper `getRowByName()` that simplifies getting a locator for a specific row. Small change to `deleteAllRepos()` helper to minimize repeating ourselves. 
- Verify that all tests in `IntrospectRepo.spec.ts` pass and test the necessary stuff listed in the related issue description.
=> HMS-5425: add PW tests for introspect repos

_playwright-tests/UI/CustomRepo.spec.ts, _playwright-tests/UI/IntrospectRepo.spec.ts, src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/SnapshotSelector.tsx
We were not able to target some elements by label. This showed to be actually bug in our code which made some elements inaccessible. According to documentation [1]:
fieldId: ID of an individual field or a group of multiple fields.
Required when a role of "group" or "radiogroup" is passed in.
If _only one field_ is included, its ID attribute and this prop _must be the same_.
[1] https://www.patternfly.org/components/forms/form/#formgroup
=> Build: Use labels correctly in FormGroup

.github/workflows/playwright-actions.yml
This changes GH action `playwright-actions` to snapshot only a single repo instead of running process-repos command for all repos. This is needed as the process-repos bogs down the test runner and tests fail/timeout because of that.
=> Test: process single repo instead of all in pw ci

src/Pages/Repositories/ContentListTable/components/AddContent/AddContent.tsx, src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx, src/Pages/Repositories/PopularRepositoriesTable/components/AddRepo.tsx
Removes prod/beta flags related to the following functionality:
- Makes it so production no longer reverses the public repository split button functionality
- Shows upload repository option in production.
I saw a bunch of sentry errors that should not be related to my changes, but just in case they are due to the node module updates (this was just dependency updates via a regular yarn install). 
Please be sure to "yarn install"  on the correct node version prior to testing.
=> HMS-5574: Remove flags for popular repo and upload repo changes

.github/workflows/content-sources-actions.yml
This adds PR head refs to all GH checkout actions that currently don't have those, this is needed so that the actions run on the same code you are pushing and they don't have different results.
=> Build: add PR head refs to github checkout actions

.gitmodules, .tekton/content-sources-frontend-pull-request.yaml, .tekton/content-sources-frontend-push.yaml, package.json
- Changes build to use a shared dockerfile (needed for konflux)
- Necessary changes described in the [ticket](https://issues.redhat.com/browse/HMS-5537) and [example PR](https://github.com/RedHatInsights/api-frontend/pull/687/files) to follow
Not sure there's anything we can test here until Konflux is working, but I would assume the pipelines should either pass or fail the same way they have before?
=> HMS-5537: use shared dockerfile

jest.config.js
This makes it so we can see results for the unit tests again, the default reporter may have been getting overridden before
Unit test results are visible in the console locally and in CI
=> Test: add default reporter to jest config

src/Pages/Templates/TemplateDetails/components/Tabs/TemplateSystemsTab.tsx
- Hide template table, pagination and input widgets when there is no template present.
- Fix: Unit test failure related to the empty state
- Its because the mock data isn't empty in the last test in current file.
- Verify that the template model in its empty state displays only the 'Add Template' widget on the page.
- Additionally, ensure that the input box is present and there is no pagination, either at the top or bottom of the page
=> HMS-5268: Clean the Template table widgets when the state is empty

_playwright-tests/UI/RedHatRepo.spec.ts
Locator was resolving to "Red Hat Insights" (top left sidebar) not just "Red Hat" tab as expected.
Tests pass
=> Fix Red Hat tab locator

src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.tsx
This fixes a bug where the warning about snapshots before the selected date was displayed in the set up date step inside of the template add modal even when use latest was selected.
When creating or editing a template the warning should not be displayed if the use latest option is selected in the set up date step.
=> HMS-5678: check for use latest on warning in the set up date step

src/Pages/Templates/TemplateDetails/components/UseTemplate/CurlTab.tsx
adds missing certs to curl command
Check that this shows with certs in the modal
=> HMS-5831: add client certs to curl command

_playwright-tests/UI/GPG_keys.spec.ts, _playwright-tests/UI/IntrospectRepo.spec.ts, _playwright-tests/UI/RedHatRepo.spec.ts, _playwright-tests/UI/UploadRepo.spec.ts, _playwright-tests/UI/helpers/navHelpers.ts
This merges test that were incorrectly split into multiple and substitutes the separation with more steps. 🧹  
Also make a small change to navigation helpers to hopefully make them a little faster. ⚡ 
Tests pass and hopefully don't time out in CI + should be less flaky due to decreased number of navigations and increased retries 🙏🏼
=> Test: merge incorrectly split tests, improve speed

src/services/Content/ContentQueries.ts
This fixes an issues where after editing a repo, the snapshot list wasn't correctly updated.
1. Create a snapshot repo.
2. Wait for valid status, check that there is 1 snapshot.
3. Edit the created repo and change the URL to a repo with different packages.
4. Wait for valid status, check that there are 2 snapshots. (**without** refreshing the page)
=> Fix: add missing invalidation for snapshot list

_playwright-tests/UI/PopularRepo.spec.ts, src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplate.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/DefineContentStep.tsx, src/Pages/Templates/TemplatesTable/components/templateHelpers.ts
Adds filters and preselected repositories in the template modal to support RHEL10 repos
1. Checkout this [backend PR](https://github.com/content-services/content-sources-backend/pull/1085)
2. Run `make repos-import && go run cmd/external-repos/main.go process-repos` to import and snapshot all repos
3. You should see the RHEL10 repos listed in the UI
4. Create a template with RHEL10 repos, this should work the same as with RHEL8 and 9
5. Filtering templates and repos on version 10 and sorting by version should also work as expected
6. EPEL10 should be listed on the Popular Repositories tab and should be able to be introspected / snapshotted
#testwith content-services/content-sources-backend#1085
=> HMS-5923: add support for rhel10

_playwright-tests/UI/RepositoryPackages.spec.ts, _playwright-tests/UI/SnapshotRepo.spec.ts
Migrate IQE Test repo package count & search
https://gitlab.cee.redhat.com/insights-qe/iqe-content-sources-plugin/-/blob/master/iqe_content_sources/tests/test_repositories.py?ref_type=heads#L915
=> HMS-6006: QE-migrate iqe test_snapshot_package_count_and_list

_playwright-tests/UI/RepositoryPackages.spec.ts
This changes the target for a kebab toggle in the `RepositoryPackages` test file, because it's currently failing when running in parallel with other tests.
Tests inside the `RepositoryPackages` should pass.
=> Test: change to correct target for kebab toggle

_playwright-tests/UI/helpers/navHelpers.ts
Without this change the locator can resolve to two locations of "Repositories", one in breadcrumbs and one in side bar. We just want the first one to be resolved in the breadcrumbs trail as a sign the page is loaded and the correct page.
tests pass
=> Fix: Add breadcrumb to navlink locator

.github/workflows/playwright-actions.yml
This fixes a bug that breaks all of our CI Playwright testing. 🐛  
This started happening after the rewrite of the external-repos CLI [[🔗](https://github.com/content-services/content-sources-backend/pull/1115)], where some of the command signatures were changed.
Tests don't fail on the RH repo not having a snapshot.
=> Test: add missing flag to RH snapshot command in CI

.github/workflows/playwright-actions.yml, _playwright-tests/UI/PopularRepo.spec.ts, src/App.tsx, src/Pages/Repositories/ContentListTable/ContentListTable.test.tsx, src/Pages/Repositories/ContentListTable/ContentListTable.tsx, src/Pages/Repositories/ContentListTable/components/ContentListFilters.test.tsx, src/Pages/Repositories/ContentListTable/components/ContentListFilters.tsx, src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContent.test.tsx, src/Pages/Repositories/ContentListTable/components/DeleteContentModal/DeleteContentModal.tsx, src/Pages/Repositories/ContentListTable/components/PackageModal/PackageModal.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/SnapshotDetailsModal.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotErrataTab.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotDetailsModal/Tabs/SnapshotPackagesTab.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.test.tsx, src/Pages/Repositories/ContentListTable/components/SnapshotListModal/SnapshotListModal.tsx, src/Pages/Repositories/PopularRepositoriesTable/PopularRepositoriesTable.tsx, src/Pages/Repositories/RepositoryLayout.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/AddTemplateContext.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/CustomRepositoriesStep.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/RedhatRepositoriesStep.tsx, src/Pages/Templates/TemplatesTable/components/AddTemplate/steps/SetUpDateStep.tsx, src/Routes/index.tsx, src/components/ZeroState/ZeroState.tsx, src/middleware/AppContext.tsx, src/services/Content/ContentApi.ts, src/services/Content/ContentQueries.ts, src/services/Features/FeatureApi.ts
* Dependent on [this backend PR](https://github.com/content-services/content-sources-backend/pull/1117)
* Adds an EPEL toggle and changes toggle behavior to be multi-select for Custom, EPEL, and Red Hat repositories
* Visibility of the Popular repositories tab and EPEL toggle is controlled with the [community repos feature](https://github.com/content-services/content-sources-backend/blob/main/configs/config.yaml.example#L173)
1. Set the [community repos feature](https://github.com/content-services/content-sources-backend/blob/main/configs/config.yaml.example#L173) to true
2. Run `make repos-import && ./release/external-repos process-repos`
3. Verify selecting/deselecting the Custom, EPEL, and Red Hat toggles shows the expected content
4. Verify the shared EPEL and Red Hat repos cannot be …
=> HMS-5828: add shared epel and remove popular repos

package.json, src/App.tsx, src/Hooks/useNotification.tsx, src/Pages/Repositories/ContentListTable/components/AddContent/helpers.ts, src/Pages/Templates/TemplateDetails/components/AddSystems/AddSystemModal.tsx, src/middleware/AppContext.tsx, src/services/Content/ContentQueries.ts, src/services/Systems/SystemsQueries.ts, src/services/Templates/TemplateQueries.ts, src/store/index.tsx, yarn.lock
- This migrates frontend-components-notifications from v5 to v6. Migration docs [here](https://github.com/RedHatInsights/frontend-components/blob/master/packages/notifications/doc/migration.md) 
- The migration also fixed the duplicate close button we were seeing on the toast notifications
- Toast notifications still work 
- Tests pass
=> HMS-6039: migrate fec-notifications from v5 to v6

_playwright-tests/style_guide.md
Fixed some typos
Using gvim I found some end-of-line whitespace
tests passs
=> Test: Fix style guide typos and end-of-line whitespace

_playwright-tests/UI/SnapshotRepo.spec.ts
This step is deleting a single repo not doing a bulk delete.
The URL will look like this for a single repo if you access the delete modal using the kebab menu:
`content/repositories/delete?repoUUID=2582bfac-7319-4a6e-bf13-34f6e01aab28`
However if you select the row and then use the dropdrown menu, the URL will just be:
`insights/content/repositories/delete`
tests pass
=> Test: Do not check for bulk delete URL when deleting a single repo

_playwright-tests/Integration/helpers/rhsmClient.ts
The proxy was not correctly being appended to the insights-client config when registering rhc in stage
=> Test: configure proxy for rhc in stage

_playwright-tests/UI/ExportSystem.spec.ts, _playwright-tests/UI/PatchBasic.spec.ts, _playwright-tests/UI/helpers/navHelpersPatch.ts
1. Patch test for exporting System.
2. Patch test Plan remediation button can not be clicked when no system is selected 
1. Navigate to the Systems all page.
2. Export by CSV/JSON.
expected_results:
2. Exported data will be downloaded.
Remediation button test
1. Navigate to the Systems all page.
2. plan remediation button can not be clicked
=> RHINENG-18926: Add patch tests and helper

src/services/Content/ContentApi.ts
Following the changes in the backend, to keep the frontend as it has been working, resumable=true was added for the /repositories/uploads api. Passing the same sha256 and chunk_size, it will still resume upload on the existing UUID.
#testwith https://github.com/content-services/content-sources-backend/pull/1176
=> HMS-8934: add resumable parameter for uploads

src/Pages/Repositories/ContentListTable/ContentListTable.tsx
Changing spinner's behavior:
- Spinner's behavior placed in the top right corner of repositories table was triggered on 4 occasions (isFetching, repositoryParamsLoading, isIntrospecting, isDeletingItems). 
- Plus even when there was no action, spinner animation kept running. 
- Except for isFetching, the other actions have different UX feedback tied to them and triggering the spinner was redundant for them.
This is now changed that spinner appears only when:
-  there is content list query data fetching going on, 
-  or content list query is polling data. 
It appears mainly on a slow connection when a user navigates between filters of the table.
For the future it would be great to redefine the placement of the spinner and the whole UX associated with it. 
Throttle your connection and …
=> HMS-8883: spinner behavior triggered only on data fetching

.github/workflows/nightly-stage-test-action.yml, _playwright-tests/Integration/PulpFixtureRepoIntrospection.spec.ts, _playwright-tests/auth.setup.ts, _playwright-tests/helpers/loginHelpers.ts, playwright_example.env
- Configure stable_sam_stage user authentication
- Add credentials to GitHub Actions workflow (.github/workflows/nightly-stage-test-action.yml)
- Update playwright environment template (playwright_example.env)
- Add authentication setup in auth.setup.ts
- Implement Pulp Fixture Repository Introspection test
- New integration test
- Validates existing Pulp project fixture repositories via API
- Uses stable_sam_stage user which has pre-existing pulp fixture repos
- Verifies repository introspection status
peer review
=> HMS-8904: Stable_sam_stage user config and Pulp fixture repo introspection

src/Pages/Templates/TemplateDetails/components/TemplateActionDropdown.tsx, src/Pages/Templates/TemplatesTable/components/DeleteTemplateModal.test.tsx, src/Pages/Templates/TemplatesTable/components/DeleteTemplateModal.tsx, src/Routes/index.tsx, src/helpers.ts
Previously when on a template details page, clicking the delete action:
- redirected to the templates list page where it was overlayed with the delete template modal. 
This might have confused users, especially when cancelling the action. 
Now the delete modal:
- is showed over the template details
- and only after the delete confirmation a user is navigated to the templates list page.
And as expected, when the delete action is triggered from the templates list page, the delete modal is overlayed over the templates list.
- navigate to a template detail, trigger delete action there, test out cancel and delete
- you can also test out that the modal is layered over the templates list page when it happens to be triggered from there
=> HMS-8608: display delete template modal over template detail page
